package br.com.deserve.menu;

import br.com.deserve.model.Parametros;
import br.com.deserve.util.LeArquivo;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.net.URL;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import org.apache.commons.net.ftp.FTPClient;
import org.apache.commons.net.ftp.FTPReply;

/**
 *
 * @author Gelson
 */
public class FrmConfig_v4 extends javax.swing.JDialog {

    URL caminhoImagem;
    Image iconeTitulo;

    private static final long serialVersionUID = -4714426361598437723L;

    public FrmConfig_v4() throws FileNotFoundException {
        initComponents();
        setLocationRelativeTo(null);
        groupButton();
        caminhoImagem = this.getClass().getClassLoader()
                .getResource("br/com/deserve/resources/Icone_SiSAD.png");
        iconeTitulo = Toolkit.getDefaultToolkit().getImage(caminhoImagem);
        setIconImage(iconeTitulo);

        LeArquivo leArq = new LeArquivo();
        Parametros param = new Parametros();
        param = leArq.readAllProperties();
        txtDiretorio.setText(param.getDir_projeto());
        txtHostFTP.setText(param.getFtp_servidor());
        txtUsuarioFTP.setText(param.getFtp_usuario());
        txtSenhaFTP.setText(param.getFtp_senha());
        txtDiretorioFTP.setText(param.getFtp_caminho());
        txtNomeEMPRESA.setText(param.getEmpresa());
        txtUsuarioEMPRESA.setText(param.getUsu_alerta());
        txtUsuarioEMPRESA.setEnabled(false);
        txtUsuarioEMPRESA.setOpaque(false);
        txtUnEMPRESA.setText(param.getUnidade_negocio());
        txtQtdeReg.setText(param.getQtde_registros());
        txtQtdeReg.setEnabled(false);
        txtQtdeReg.setOpaque(false);
        if (System.getenv("KETTLE_HOME").equals("")) {
            jLabelKettle_Home.setText("Nao encontrada!");
        } else {
            txtKettleH.setText(System.getenv("KETTLE_HOME"));
        }

        String kettle_home = System.getenv("KETTLE_HOME");
        if (kettle_home.equals("")) {
            jLabelKettle_Home.setText("Nao encontrada!");
        } else {
            jLabelKettle_Home.setText(kettle_home);
        }

        String java_home = System.getenv("JAVA_HOME");
        if (java_home.equals("")) {
            jLabelJava_Home.setText("Nao encontrada!");
        } else {
            jLabelJava_Home.setText(java_home);
        }

        @SuppressWarnings("unused")
        LeArquivo leArq1 = new LeArquivo();
        Parametros param1 = new Parametros();
        if (!leArq1.readAllProperties().equals(null)) {
            param1 = leArq1.readAllProperties();
        } else {
            String msg = ("Arquivo de propriedades nao encontrado!");
            JOptionPane.showMessageDialog(this, msg, null, WIDTH);
        }
        String diretorio = param1.getDir_projeto();
        if (diretorio.equals("")) {
            jLabelDirProjeto
                    .setText("C:\\SiSAD\\data-integration\\Projetos\\MATRIZ\\");
        } else {
            this.jLabelDirProjeto.setText(txtDiretorio.getText());
            this.jLabelDirProjeto.repaint();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed"
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanelPrincipal = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtDiretorio = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelBD = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtHost = new javax.swing.JTextField();
        txtDatabase = new javax.swing.JTextField();
        txtUser = new javax.swing.JTextField();
        jRadioMatriz = new javax.swing.JRadioButton();
        jRadioFilial = new javax.swing.JRadioButton();
        jRadioDatacenter = new javax.swing.JRadioButton();
        txtSchema = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jCheckBoxOracle = new javax.swing.JCheckBox();
        jCheckBoxMSSQL = new javax.swing.JCheckBox();
        jButtonConexao = new javax.swing.JButton();
        jLabelTesteConexao = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        jPanelFTP = new javax.swing.JPanel();
        jLabelHost = new javax.swing.JLabel();
        jLabelUsuario = new javax.swing.JLabel();
        jLabelSenha = new javax.swing.JLabel();
        jLabelDiretorio = new javax.swing.JLabel();
        txtHostFTP = new javax.swing.JTextField();
        txtUsuarioFTP = new javax.swing.JTextField();
        txtDiretorioFTP = new javax.swing.JTextField();
        jButtonConexaoFTP = new javax.swing.JButton();
        jLabelTesteFTP = new javax.swing.JLabel();
        txtSenhaFTP = new javax.swing.JPasswordField();
        jPanelEmpresa = new javax.swing.JPanel();
        jLabelHost1 = new javax.swing.JLabel();
        jLabelUsuario1 = new javax.swing.JLabel();
        jLabelSenha1 = new javax.swing.JLabel();
        txtNomeEMPRESA = new javax.swing.JTextField();
        txtUsuarioEMPRESA = new javax.swing.JTextField();
        txtUnEMPRESA = new javax.swing.JTextField();
        jPanelObs = new javax.swing.JPanel();
        jLabelQtdeReg = new javax.swing.JLabel();
        txtQtdeReg = new javax.swing.JTextField();
        jLabelKettleH = new javax.swing.JLabel();
        txtKettleH = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabelKettle_Home = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabelJava_Home = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabelDirProjeto = new javax.swing.JLabel();
        jLabelLogo = new javax.swing.JLabel();
        jLInf_Versao = new javax.swing.JLabel();
        jCBAlteraVersao = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SiSAD v4");
        setBackground(new java.awt.Color(0, 0, 255));
        setResizable(false);

        jLabel1.setText("Endereço projeto:");

        txtDiretorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiretorioActionPerformed(evt);
            }
        });

        jButton1.setMnemonic('S');
        jButton1.setText("SAIR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Host Name:");

        jLabel4.setText("Database Name:");

        jLabel5.setText("User Name:");

        jLabel6.setText("Password:");

        txtHost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHostActionPerformed(evt);
            }
        });

        txtDatabase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDatabaseActionPerformed(evt);
            }
        });

        jRadioMatriz.setMnemonic('M');
        jRadioMatriz.setText("Matriz");
        jRadioMatriz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioMatrizActionPerformed(evt);
            }
        });

        jRadioFilial.setMnemonic('F');
        jRadioFilial.setText("Filial");
        jRadioFilial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioFilialActionPerformed(evt);
            }
        });

        jRadioDatacenter.setMnemonic('D');
        jRadioDatacenter.setText("Datacenter");
        jRadioDatacenter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioDatacenterActionPerformed(evt);
            }
        });

        jLabel7.setText("Schema:");

        buttonGroup1.add(jCheckBoxOracle);
        jCheckBoxOracle.setText("Oracle");
        jCheckBoxOracle.setEnabled(false);

        buttonGroup1.add(jCheckBoxMSSQL);
        jCheckBoxMSSQL.setText("MS-SQL");
        jCheckBoxMSSQL.setEnabled(false);

        jButtonConexao.setMnemonic('C');
        jButtonConexao.setText("Conectar");
        jButtonConexao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConexaoActionPerformed(evt);
            }
        });

        jLabelTesteConexao.setForeground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout jPanelBDLayout = new javax.swing.GroupLayout(jPanelBD);
        jPanelBD.setLayout(jPanelBDLayout);
        jPanelBDLayout.setHorizontalGroup(
            jPanelBDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBDLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelBDLayout.createSequentialGroup()
                        .addComponent(jRadioMatriz)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioFilial)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioDatacenter)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 187, Short.MAX_VALUE)
                        .addComponent(jButtonConexao))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBDLayout.createSequentialGroup()
                        .addGroup(jPanelBDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addComponent(jLabel7)
                            .addGroup(jPanelBDLayout.createSequentialGroup()
                                .addComponent(jCheckBoxOracle)
                                .addGap(18, 18, 18)
                                .addComponent(jCheckBoxMSSQL))
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelBDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtUser)
                            .addComponent(txtDatabase)
                            .addComponent(txtHost)
                            .addComponent(txtSchema, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelTesteConexao, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                            .addComponent(txtPassword))))
                .addContainerGap())
        );
        jPanelBDLayout.setVerticalGroup(
            jPanelBDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBDLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioMatriz)
                    .addComponent(jRadioFilial)
                    .addComponent(jRadioDatacenter)
                    .addComponent(jButtonConexao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelBDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jCheckBoxOracle)
                        .addComponent(jCheckBoxMSSQL))
                    .addComponent(jLabelTesteConexao, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanelBDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelBDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDatabase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelBDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                    .addComponent(txtPassword))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSchema, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelBDLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel3, jLabel4, jLabel5, jLabel6, jLabel7, txtDatabase, txtHost, txtSchema, txtUser});

        jTabbedPane1.addTab("", new javax.swing.ImageIcon(getClass().getResource("/br/com/deserve/resources/bd.jpg")), jPanelBD, "Banco de Dados"); // NOI18N
        jPanelBD.getAccessibleContext().setAccessibleName("bd");
        jPanelBD.getAccessibleContext().setAccessibleDescription("");

        jLabelHost.setText("Host Name:");

        jLabelUsuario.setText("Usuario:");

        jLabelSenha.setText("Senha:");

        jLabelDiretorio.setText("Diretorio FTP:");

        txtHostFTP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHostFTPActionPerformed(evt);
            }
        });

        jButtonConexaoFTP.setMnemonic('C');
        jButtonConexaoFTP.setText("Conectar");
        jButtonConexaoFTP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConexaoFTPActionPerformed(evt);
            }
        });

        jLabelTesteFTP.setForeground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout jPanelFTPLayout = new javax.swing.GroupLayout(jPanelFTP);
        jPanelFTP.setLayout(jPanelFTPLayout);
        jPanelFTPLayout.setHorizontalGroup(
            jPanelFTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFTPLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelFTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFTPLayout.createSequentialGroup()
                        .addGroup(jPanelFTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelHost)
                            .addComponent(jLabelUsuario)
                            .addComponent(jLabelSenha)
                            .addComponent(jLabelDiretorio))
                        .addGap(18, 30, Short.MAX_VALUE)
                        .addGroup(jPanelFTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtUsuarioFTP, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                            .addComponent(txtDiretorioFTP, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                            .addComponent(txtHostFTP, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                            .addComponent(txtSenhaFTP)))
                    .addComponent(jLabelTesteFTP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(44, 44, 44)
                .addComponent(jButtonConexaoFTP)
                .addGap(20, 20, 20))
        );

        jPanelFTPLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtDiretorioFTP, txtHostFTP, txtUsuarioFTP});

        jPanelFTPLayout.setVerticalGroup(
            jPanelFTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFTPLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelFTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFTPLayout.createSequentialGroup()
                        .addComponent(jButtonConexaoFTP)
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFTPLayout.createSequentialGroup()
                        .addComponent(jLabelTesteFTP, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(jPanelFTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelFTPLayout.createSequentialGroup()
                        .addComponent(jLabelHost)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelUsuario)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelSenha))
                    .addGroup(jPanelFTPLayout.createSequentialGroup()
                        .addComponent(txtHostFTP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtUsuarioFTP, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtSenhaFTP, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelFTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelDiretorio)
                    .addComponent(txtDiretorioFTP, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("", new javax.swing.ImageIcon(getClass().getResource("/br/com/deserve/resources/ftp.jpg")), jPanelFTP, "FTP"); // NOI18N
        jPanelFTP.getAccessibleContext().setAccessibleName("ftp");

        jLabelHost1.setText("Nome Empresa:");

        jLabelUsuario1.setText("Usuario Alerta:");

        jLabelSenha1.setText("Unidade Negocio:");

        javax.swing.GroupLayout jPanelEmpresaLayout = new javax.swing.GroupLayout(jPanelEmpresa);
        jPanelEmpresa.setLayout(jPanelEmpresaLayout);
        jPanelEmpresaLayout.setHorizontalGroup(
            jPanelEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelEmpresaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelSenha1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelHost1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelUsuario1, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(26, 26, 26)
                .addGroup(jPanelEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtNomeEMPRESA, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUsuarioEMPRESA, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUnEMPRESA, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(130, Short.MAX_VALUE))
        );
        jPanelEmpresaLayout.setVerticalGroup(
            jPanelEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEmpresaLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanelEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelEmpresaLayout.createSequentialGroup()
                        .addComponent(txtNomeEMPRESA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64))
                    .addGroup(jPanelEmpresaLayout.createSequentialGroup()
                        .addComponent(txtUsuarioEMPRESA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtUnEMPRESA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelEmpresaLayout.createSequentialGroup()
                        .addComponent(jLabelHost1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelUsuario1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelSenha1)))
                .addContainerGap(132, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("", new javax.swing.ImageIcon(getClass().getResource("/br/com/deserve/resources/empresa.jpg")), jPanelEmpresa, "Empresa"); // NOI18N
        jPanelEmpresa.getAccessibleContext().setAccessibleName("empresa");

        jLabelQtdeReg.setText("Qtde. Registros a processar:");

        txtQtdeReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQtdeRegActionPerformed(evt);
            }
        });

        jLabelKettleH.setText("Kettle_Home");

        txtKettleH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKettleHActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelObsLayout = new javax.swing.GroupLayout(jPanelObs);
        jPanelObs.setLayout(jPanelObsLayout);
        jPanelObsLayout.setHorizontalGroup(
            jPanelObsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelObsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelObsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelQtdeReg)
                    .addComponent(jLabelKettleH))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelObsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtKettleH, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtQtdeReg, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanelObsLayout.setVerticalGroup(
            jPanelObsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelObsLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanelObsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtQtdeReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelQtdeReg))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelObsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelKettleH)
                    .addComponent(txtKettleH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(158, Short.MAX_VALUE))
        );

        jPanelObsLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabelQtdeReg, txtQtdeReg});

        jPanelObsLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabelKettleH, txtKettleH});

        jTabbedPane1.addTab("", new javax.swing.ImageIcon(getClass().getResource("/br/com/deserve/resources/utilitarios.jpg")), jPanelObs, "Configurações Extras"); // NOI18N
        jPanelObs.getAccessibleContext().setAccessibleName("obs");

        jButton3.setMnemonic('A');
        jButton3.setText("ALTERAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabelKettle_Home.setForeground(new java.awt.Color(0, 102, 102));

        jLabel2.setText("Kettle_Home:");

        jLabel8.setText("Java_Home:");

        jLabel9.setText("Endereço atual:");

        jLabelDirProjeto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/deserve/resources/SISAD.jpg"))); // NOI18N
        jLabelLogo.setText("jLabel10");

        jLInf_Versao.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLInf_Versao.setForeground(java.awt.Color.red);
        jLInf_Versao.setText("Versão 4");

        jCBAlteraVersao.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Alterar versão", "SiSAD v5" }));
        jCBAlteraVersao.setToolTipText("");
        jCBAlteraVersao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBAlteraVersaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelPrincipalLayout = new javax.swing.GroupLayout(jPanelPrincipal);
        jPanelPrincipal.setLayout(jPanelPrincipalLayout);
        jPanelPrincipalLayout.setHorizontalGroup(
            jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPrincipalLayout.createSequentialGroup()
                        .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtDiretorio)
                            .addComponent(jLabelDirProjeto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(75, 75, 75))
                    .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                        .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabelKettle_Home, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel8))
                            .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabelJava_Home, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPrincipalLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLInf_Versao))
                                    .addComponent(jLabelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(32, 32, 32))
                            .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jCBAlteraVersao, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );

        jPanelPrincipalLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton1, jButton3, jCBAlteraVersao});

        jPanelPrincipalLayout.setVerticalGroup(
            jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtDiretorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelDirProjeto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelKettle_Home, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelJava_Home, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTabbedPane1))
                    .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLInf_Versao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jCBAlteraVersao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(jButton3)
                        .addGap(11, 11, 11)
                        .addComponent(jButton1)))
                .addContainerGap())
        );

        jPanelPrincipalLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel9, jLabelDirProjeto});

        jTabbedPane1.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(681, 455));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jCBAlteraVersaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBAlteraVersaoActionPerformed
        int a = jCBAlteraVersao.getSelectedIndex();
        if (a == 1) {
            try {
                this.setVisible(false);
                FrmConfig_v5 frm5 = new FrmConfig_v5();

                frm5.setLocationRelativeTo(null);
                frm5.setVisible(true);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(FrmConfig_v4.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jCBAlteraVersaoActionPerformed

    private void txtDiretorioActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtDiretorioActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_txtDiretorioActionPerformed

    // sair
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed

        this.setVisible(false);
        Runtime.getRuntime().exit(0);

    }// GEN-LAST:event_jButton1ActionPerformed
    // alterar

    @SuppressWarnings("deprecation")
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton3ActionPerformed
        LeArquivo leArq = new LeArquivo();
        leArq.readAllProperties();

        String diretorio = (txtDiretorio.getText());
        if (txtDiretorio.getText().equals("")) {
            JOptionPane
                    .showMessageDialog(this, "Adicione o caminho do projeto");
            txtDiretorio.requestFocus();
            return;
        }
        leArq.writeProperties(diretorio);
        jLabelDirProjeto.setText(diretorio);

        String empresa = (txtNomeEMPRESA.getText());
        if (txtNomeEMPRESA.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Adicione o nome da Empresa");
            txtNomeEMPRESA.requestFocus();
            return;
        }

        String usrAlerta = (txtUsuarioEMPRESA.getText());
        if (txtUsuarioEMPRESA.getText().equals("")) {
            JOptionPane.showMessageDialog(this,
                    "Adicione um codigo de usuario Cigam");
            txtUsuarioEMPRESA.requestFocus();
            return;
        }

        String unNegocio = (txtUnEMPRESA.getText());
        if (txtUnEMPRESA.getText().equals("")) {
            JOptionPane
                    .showMessageDialog(this, "Adicione a Unidade de Negocio");
            txtUnEMPRESA.requestFocus();
            return;
        }
        leArq.writeEMPRESA(empresa, usrAlerta, unNegocio);

        String ftpHost = (txtHostFTP.getText());
        String ftpUsr = (txtUsuarioFTP.getText());
        String ftpSenha = (txtSenhaFTP.getText());
        String ftpDiretorio = (txtDiretorioFTP.getText());
        leArq.writeFTP(ftpHost, ftpUsr, ftpSenha, ftpDiretorio);

        String kettle = (txtKettleH.getText());
        String qtdRegistros = (txtQtdeReg.getText());
        leArq.writeOBS(qtdRegistros, kettle);

        if (jRadioMatriz.isSelected()) {

            String host = (txtHost.getText());
            if (txtHost.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Adicione o Host");
                txtHost.requestFocus();
                return;
            }
            String database = (txtDatabase.getText());
            if (txtDatabase.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Adicione o Database");
                txtDatabase.requestFocus();
                return;
            }
            String user = (txtUser.getText());
            if (txtUser.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Adicione o Usuario");
                txtUser.requestFocus();
                return;
            }
            String password = (txtPassword.getText());
            if (txtPassword.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Adicione a Senha");
                txtPassword.requestFocus();
                return;
            }
            String schema = (txtSchema.getText());
            if (txtSchema.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Adicione o Schema");
                txtSchema.requestFocus();
                return;
            }
            leArq.writeBDMatriz(host, database, user, password, schema);

        }

        if (jRadioFilial.isSelected()) {

            String host = (txtHost.getText());
            if (txtHost.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Adicione o Host");
                txtHost.requestFocus();
                return;
            }
            String database = (txtDatabase.getText());
            if (txtDatabase.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Adicione o Database");
                txtDatabase.requestFocus();
                return;
            }
            String user = (txtUser.getText());
            if (txtUser.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Adicione o Usuario");
                txtUser.requestFocus();
                return;
            }
            String password = (txtPassword.getText());
            if (txtPassword.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Adicione a Senha");
                txtPassword.requestFocus();
                return;
            }
            String schema = (txtSchema.getText());
            if (txtSchema.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Adicione o Schema");
                txtSchema.requestFocus();
                return;
            }
            leArq.writeBDFilial(host, database, user, password, schema);

        }

        if (jRadioDatacenter.isSelected()) {

            String host = (txtHost.getText());
            if (txtHost.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Adicione o Host");
                txtHost.requestFocus();
                return;
            }
            String database = (txtDatabase.getText());
            if (txtDatabase.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Adicione o Database");
                txtDatabase.requestFocus();
                return;
            }
            String user = (txtUser.getText());
            if (txtUser.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Adicione o Usuario");
                txtUser.requestFocus();
                return;
            }
            String password = (txtPassword.getText());
            if (txtPassword.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Adicione a Senha");
                txtPassword.requestFocus();
                return;
            }
            String schema = (txtSchema.getText());
            leArq.writeBDDatacenter(host, database, user, password, schema);

        }

        setVisible(true);
    }// GEN-LAST:event_jButton3ActionPerformed
    // carregar dados

    private void txtQtdeRegActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtQtdeRegActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_txtQtdeRegActionPerformed

    private void txtKettleHActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtKettleHActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_txtKettleHActionPerformed

    private void jRadioFilialActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jRadioFilialActionPerformed

        jLabelTesteConexao.setText("");
        LeArquivo leArq = new LeArquivo();
        Parametros param = new Parametros();
        param = leArq.readAllProperties();

        if (jRadioFilial.isSelected()) {

            txtHost.setText(param.getEscravo_servidor());
            txtDatabase.setText(param.getEscravo_database());
            txtUser.setText(param.getEscravo_usuario());
            txtPassword.setText(param.getEscravo_senha());
            txtSchema.setText(param.getSchema_escravo());

            jCheckBoxOracle.setEnabled(true);
            jCheckBoxMSSQL.setEnabled(true);

        }

    }// GEN-LAST:event_jRadioFilialActionPerformed

    private void txtDatabaseActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtDatabaseActionPerformed

    }// GEN-LAST:event_txtDatabaseActionPerformed

    private void txtHostActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtHostActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_txtHostActionPerformed

    private void jButtonConexaoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonConexaoActionPerformed

        if (jRadioDatacenter.isSelected()) {

            jButtonConexao.setCursor(Cursor
                    .getPredefinedCursor(Cursor.WAIT_CURSOR));
            LeArquivo leArq = new LeArquivo();
            Parametros param = new Parametros();
            param = leArq.readAllProperties();

            try {
                Class.forName("com.mysql.jdbc.Driver");
                jLabelTesteConexao.setForeground(Color.BLUE);
                jLabelTesteConexao.setText("Conectado! Usuario: "
                        + param.getDatacenter_usuario());
                DriverManager.getConnection(
                        "jdbc:mysql://" + param.getDatacenter_servidor()
                        + ":3306/" + param.getDatacenter_database(),
                        param.getDatacenter_usuario(),
                        param.getDatacenter_senha());
            } catch (ClassNotFoundException e) {
                jLabelTesteConexao.setForeground(Color.RED);
                jLabelTesteConexao.setText("Falta adicionar o driver.");
                jButtonConexao.setCursor(Cursor
                        .getPredefinedCursor(Cursor.DEFAULT_CURSOR));

            } catch (SQLException ex) {
                jLabelTesteConexao.setForeground(Color.RED);
                if (ex.getMessage().length() > 40) {
                    jLabelTesteConexao
                            .setText(ex.getMessage().substring(0, 40));
                } else {
                    jLabelTesteConexao.setText(ex.getMessage());
                }
                jButtonConexao.setCursor(Cursor
                        .getPredefinedCursor(Cursor.DEFAULT_CURSOR));
                Logger.getLogger(FrmConfig_v4.class.getName()).log(Level.SEVERE,
                        null, ex);
            }
            jButtonConexao.setCursor(Cursor
                    .getPredefinedCursor(Cursor.DEFAULT_CURSOR));
        }

        if (jRadioMatriz.isSelected()) {

            if (jCheckBoxOracle.isSelected() || jCheckBoxMSSQL.isSelected()) {

                jButtonConexao.setCursor(Cursor
                        .getPredefinedCursor(Cursor.WAIT_CURSOR));

                if (jCheckBoxOracle.isSelected()) {

                    LeArquivo leArq = new LeArquivo();
                    Parametros param = new Parametros();
                    param = leArq.readAllProperties();

                    try {
                        Class.forName("oracle.jdbc.driver.OracleDriver");
                        jLabelTesteConexao.setForeground(Color.BLUE);
                        jLabelTesteConexao.setText("Conectado! Usuario: "
                                + param.getMestre_usuario());
                        DriverManager.getConnection(
                                "jdbc:oracle:thin:@"
                                + param.getMestre_servidor() + ":1521:"
                                + param.getMestre_database(),
                                param.getMestre_usuario(),
                                param.getMestre_senha());
                    } catch (ClassNotFoundException e) {
                        jLabelTesteConexao.setForeground(Color.RED);
                        jLabelTesteConexao.setText("Falta adicionar o driver.");
                        jButtonConexao.setCursor(Cursor
                                .getPredefinedCursor(Cursor.DEFAULT_CURSOR));

                    } catch (SQLException ex) {
                        jLabelTesteConexao.setForeground(Color.RED);
                        jLabelTesteConexao.setForeground(Color.RED);
                        if (ex.getMessage().length() > 40) {
                            jLabelTesteConexao.setText(ex.getMessage()
                                    .substring(0, 40));
                        } else {
                            jLabelTesteConexao.setText(ex.getMessage());
                        }
                        jButtonConexao.setCursor(Cursor
                                .getPredefinedCursor(Cursor.DEFAULT_CURSOR));
                        Logger.getLogger(FrmConfig_v4.class.getName()).log(
                                Level.SEVERE, null, ex);
                    }
                    jButtonConexao.setCursor(Cursor
                            .getPredefinedCursor(Cursor.DEFAULT_CURSOR));
                }
                if (jCheckBoxMSSQL.isSelected()) {

                    LeArquivo leArq = new LeArquivo();
                    Parametros param = new Parametros();
                    param = leArq.readAllProperties();

                    try {
                        Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                        jLabelTesteConexao.setForeground(Color.BLUE);
                        jLabelTesteConexao.setText("Conectado! Usuario: "
                                + param.getMestre_usuario());
                        DriverManager.getConnection(
                                "jdbc:sqlserver://"
                                + param.getMestre_servidor() + ":1433;"
                                + "databaseName="
                                + param.getMestre_database() + ";",
                                param.getMestre_usuario(),
                                param.getMestre_senha());
                    } catch (ClassNotFoundException e) {
                        jLabelTesteConexao.setForeground(Color.RED);
                        jLabelTesteConexao.setText("Falta adicionar o driver.");
                        jButtonConexao.setCursor(Cursor
                                .getPredefinedCursor(Cursor.DEFAULT_CURSOR));

                    } catch (SQLException ex) {
                        jLabelTesteConexao.setForeground(Color.RED);
                        jLabelTesteConexao.setForeground(Color.RED);
                        if (ex.getMessage().length() > 40) {
                            jLabelTesteConexao.setText(ex.getMessage()
                                    .substring(0, 40));
                        } else {
                            jLabelTesteConexao.setText(ex.getMessage());
                        }
                        jButtonConexao.setCursor(Cursor
                                .getPredefinedCursor(Cursor.DEFAULT_CURSOR));
                        Logger.getLogger(FrmConfig_v4.class.getName()).log(
                                Level.SEVERE, null, ex);
                    }
                    jButtonConexao.setCursor(Cursor
                            .getPredefinedCursor(Cursor.DEFAULT_CURSOR));

                }
            } else {
                jLabelTesteConexao.setForeground(Color.RED);
                jLabelTesteConexao
                        .setText("E necessario selecionar um tipo de BD.");
                jButtonConexao.setCursor(Cursor
                        .getPredefinedCursor(Cursor.DEFAULT_CURSOR));
            }

        }

        if (jRadioFilial.isSelected()) {

            if (jCheckBoxOracle.isSelected() || jCheckBoxMSSQL.isSelected()) {

                jButtonConexao.setCursor(Cursor
                        .getPredefinedCursor(Cursor.WAIT_CURSOR));

                if (jCheckBoxOracle.isSelected()) {

                    LeArquivo leArq = new LeArquivo();
                    Parametros param = new Parametros();
                    param = leArq.readAllProperties();

                    try {
                        Class.forName("oracle.jdbc.driver.OracleDriver");
                        jLabelTesteConexao.setForeground(Color.BLUE);
                        jLabelTesteConexao.setText("Conectado! Usuario: "
                                + param.getEscravo_usuario());
                        DriverManager.getConnection("jdbc:oracle:thin:@"
                                + param.getEscravo_servidor() + ":1521:"
                                + param.getEscravo_database(),
                                param.getEscravo_usuario(),
                                param.getEscravo_senha());
                    } catch (ClassNotFoundException e) {
                        jLabelTesteConexao.setForeground(Color.RED);
                        jLabelTesteConexao.setText("Falta adicionar o driver.");
                        jButtonConexao.setCursor(Cursor
                                .getPredefinedCursor(Cursor.DEFAULT_CURSOR));

                    } catch (SQLException ex) {
                        jLabelTesteConexao.setForeground(Color.RED);
                        jLabelTesteConexao.setForeground(Color.RED);
                        if (ex.getMessage().length() > 40) {
                            jLabelTesteConexao.setText(ex.getMessage()
                                    .substring(0, 40));
                        } else {
                            jLabelTesteConexao.setText(ex.getMessage());
                        }
                        jButtonConexao.setCursor(Cursor
                                .getPredefinedCursor(Cursor.DEFAULT_CURSOR));
                        Logger.getLogger(FrmConfig_v4.class.getName()).log(
                                Level.SEVERE, null, ex);
                    }
                    jButtonConexao.setCursor(Cursor
                            .getPredefinedCursor(Cursor.DEFAULT_CURSOR));
                }

                if (jCheckBoxMSSQL.isSelected()) {

                    LeArquivo leArq = new LeArquivo();
                    Parametros param = new Parametros();
                    param = leArq.readAllProperties();

                    try {
                        Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                        jLabelTesteConexao.setForeground(Color.BLUE);
                        jLabelTesteConexao.setText("Conectado! Usuario: "
                                + param.getEscravo_usuario());
                        DriverManager.getConnection(
                                "jdbc:sqlserver://"
                                + param.getEscravo_servidor()
                                + ":1433;" + "databaseName="
                                + param.getEscravo_database() + ";",
                                param.getEscravo_usuario(),
                                param.getEscravo_senha());
                    } catch (ClassNotFoundException e) {
                        jLabelTesteConexao.setForeground(Color.RED);
                        jLabelTesteConexao.setText("Falta adicionar o driver.");
                        jButtonConexao.setCursor(Cursor
                                .getPredefinedCursor(Cursor.DEFAULT_CURSOR));

                    } catch (SQLException ex) {
                        jLabelTesteConexao.setForeground(Color.RED);
                        jLabelTesteConexao.setForeground(Color.RED);
                        if (ex.getMessage().length() > 40) {
                            jLabelTesteConexao.setText(ex.getMessage()
                                    .substring(0, 40));
                        } else {
                            jLabelTesteConexao.setText(ex.getMessage());
                        }
                        jButtonConexao.setCursor(Cursor
                                .getPredefinedCursor(Cursor.DEFAULT_CURSOR));
                        Logger.getLogger(FrmConfig_v4.class.getName()).log(
                                Level.SEVERE, null, ex);
                    }
                    jButtonConexao.setCursor(Cursor
                            .getPredefinedCursor(Cursor.DEFAULT_CURSOR));

                }

            } else {
                jLabelTesteConexao.setForeground(Color.RED);
                jLabelTesteConexao
                        .setText("E necessario selecionar um tipo de BD.");
                jButtonConexao.setCursor(Cursor
                        .getPredefinedCursor(Cursor.DEFAULT_CURSOR));
            }
        }

    }// GEN-LAST:event_jButtonConexaoActionPerformed

    private void jRadioMatrizActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jRadioMatrizActionPerformed

        jLabelTesteConexao.setText("");
        LeArquivo leArq = new LeArquivo();
        Parametros param = new Parametros();
        param = leArq.readAllProperties();

        if (jRadioMatriz.isSelected()) {

            txtHost.setText(param.getMestre_servidor());
            txtDatabase.setText(param.getMestre_database());
            txtUser.setText(param.getMestre_usuario());
            txtPassword.setText(param.getMestre_senha());
            txtSchema.setText(param.getSchema_mestre());

            jCheckBoxOracle.setEnabled(true);
            jCheckBoxMSSQL.setEnabled(true);

        }

    }// GEN-LAST:event_jRadioMatrizActionPerformed

    private void jRadioDatacenterActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jRadioDatacenterActionPerformed

        jLabelTesteConexao.setText("");
        LeArquivo leArq = new LeArquivo();
        Parametros param = new Parametros();
        param = leArq.readAllProperties();

        if (jRadioDatacenter.isSelected()) {

            txtHost.setText(param.getDatacenter_servidor());
            txtDatabase.setText(param.getDatacenter_database());
            txtUser.setText(param.getDatacenter_usuario());
            txtPassword.setText(param.getDatacenter_senha());
            txtSchema.setText(param.getSchema_datacenter());

            jCheckBoxOracle.setEnabled(false);
            jCheckBoxMSSQL.setEnabled(false);

        }

    }// GEN-LAST:event_jRadioDatacenterActionPerformed

    private void jButtonConexaoFTPActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonConexaoFTPActionPerformed

        jButtonConexaoFTP.setCursor(Cursor
                .getPredefinedCursor(Cursor.WAIT_CURSOR));
        LeArquivo leArq = new LeArquivo();
        Parametros param = new Parametros();
        param = leArq.readAllProperties();

        @SuppressWarnings("unused")
        FTPClient ftp = new FTPClient();

        String server = param.getFtp_servidor();
        int port = 21;
        String user = param.getFtp_usuario();
        String pass = param.getFtp_senha();
        String caminhoFTP = param.getFtp_caminho();
        FTPClient ftpClient = new FTPClient();
        try {
            ftpClient.connect(server, port);
            showServerReply(ftpClient);
            int replyCode = ftpClient.getReplyCode();
            if (!FTPReply.isPositiveCompletion(replyCode)) {
                jLabelTesteFTP.setForeground(Color.RED);
                jLabelTesteFTP
                        .setText("A operacao falhou. Resposta do servidor: "
                                + replyCode);
                jButtonConexaoFTP.setCursor(Cursor
                        .getPredefinedCursor(Cursor.DEFAULT_CURSOR));
                return;
            }
            boolean success = ftpClient.login(user, pass);
            showServerReply(ftpClient);
            if (!success) {
                jLabelTesteFTP.setForeground(Color.RED);
                jLabelTesteFTP.setText("Usuario ou senha incorretos");
                jButtonConexaoFTP.setCursor(Cursor
                        .getPredefinedCursor(Cursor.DEFAULT_CURSOR));
                return;
            } else {
                if (!ftpClient.changeWorkingDirectory(caminhoFTP)) {
                    jLabelTesteFTP.setForeground(Color.RED);
                    jLabelTesteFTP
                            .setText("Logou no servidor, mas o diretorio nao existe!");
                    return;
                } else {
                    jLabelTesteFTP.setForeground(Color.BLUE);
                    jLabelTesteFTP
                            .setText("Logou no servidor e diretorio existe!");
                }
                ftpClient.logout();
                jButtonConexaoFTP.setCursor(Cursor
                        .getPredefinedCursor(Cursor.DEFAULT_CURSOR));
            }
        } catch (IOException ex) {
            jLabelTesteFTP.setForeground(Color.RED);
            jLabelTesteFTP
                    .setText("Nao conectou! FTP off-line ou endereco incorreto!");
            jButtonConexaoFTP.setCursor(Cursor
                    .getPredefinedCursor(Cursor.DEFAULT_CURSOR));
            ex.printStackTrace();
        }

    }// GEN-LAST:event_jButtonConexaoFTPActionPerformed

    private void txtHostFTPActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtHostFTPActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_txtHostFTPActionPerformed

    private void groupButton() {
        buttonGroup1 = new ButtonGroup();
        buttonGroup1.add(jRadioMatriz);
        buttonGroup1.add(jRadioFilial);
        buttonGroup1.add(jRadioDatacenter);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonConexao;
    private javax.swing.JButton jButtonConexaoFTP;
    private javax.swing.JComboBox jCBAlteraVersao;
    private javax.swing.JCheckBox jCheckBoxMSSQL;
    private javax.swing.JCheckBox jCheckBoxOracle;
    private javax.swing.JLabel jLInf_Versao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelDirProjeto;
    private javax.swing.JLabel jLabelDiretorio;
    private javax.swing.JLabel jLabelHost;
    private javax.swing.JLabel jLabelHost1;
    private javax.swing.JLabel jLabelJava_Home;
    private javax.swing.JLabel jLabelKettleH;
    private javax.swing.JLabel jLabelKettle_Home;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JLabel jLabelQtdeReg;
    private javax.swing.JLabel jLabelSenha;
    private javax.swing.JLabel jLabelSenha1;
    private javax.swing.JLabel jLabelTesteConexao;
    private javax.swing.JLabel jLabelTesteFTP;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JLabel jLabelUsuario1;
    private javax.swing.JPanel jPanelBD;
    private javax.swing.JPanel jPanelEmpresa;
    private javax.swing.JPanel jPanelFTP;
    private javax.swing.JPanel jPanelObs;
    private javax.swing.JPanel jPanelPrincipal;
    private javax.swing.JRadioButton jRadioDatacenter;
    private javax.swing.JRadioButton jRadioFilial;
    private javax.swing.JRadioButton jRadioMatriz;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField txtDatabase;
    private javax.swing.JTextField txtDiretorio;
    private javax.swing.JTextField txtDiretorioFTP;
    private javax.swing.JTextField txtHost;
    private javax.swing.JTextField txtHostFTP;
    private javax.swing.JTextField txtKettleH;
    private javax.swing.JTextField txtNomeEMPRESA;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtQtdeReg;
    private javax.swing.JTextField txtSchema;
    private javax.swing.JPasswordField txtSenhaFTP;
    private javax.swing.JTextField txtUnEMPRESA;
    private javax.swing.JTextField txtUser;
    private javax.swing.JTextField txtUsuarioEMPRESA;
    private javax.swing.JTextField txtUsuarioFTP;
    // End of variables declaration//GEN-END:variables

    private void showServerReply(FTPClient ftpClient) {
        String[] replies = ftpClient.getReplyStrings();
        if (replies != null && replies.length > 0) {
            for (String aReply : replies) {
                System.out.println("SERVER: " + aReply);
            }
        }
    }

}
