/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.deserve.menu;

import java.awt.Image;
import java.awt.Toolkit;
import java.io.FileNotFoundException;
import java.net.URL;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author gelson
 */
public class FrmLoggin extends javax.swing.JFrame {

    private static final long serialVersionUID = -6666418552725585974L;
    URL caminhoImagem;
    Image iconeTitulo;

    /**
     * Creates new form Loggin
     */
    public FrmLoggin() {
        initComponents();
        setLocationRelativeTo(null);
        getRootPane().setDefaultButton(jButtonEntrar);
        caminhoImagem = this.getClass().getClassLoader()
                .getResource("br/com/deserve/resources/Icone_SiSAD.png");
        iconeTitulo = Toolkit.getDefaultToolkit().getImage(caminhoImagem);
        setIconImage(iconeTitulo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void initComponents() {

        jLUsuario = new javax.swing.JLabel();
        jLSenha = new javax.swing.JLabel();
        jTFUsuario = new javax.swing.JTextField();
        jButtonSair = new javax.swing.JButton();
        jButtonEntrar = new javax.swing.JButton();
        jTFSenha = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Configurador SiSAD ");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(300, 200));
        setMinimumSize(new java.awt.Dimension(265, 155));
        setResizable(false);

        jLUsuario.setText("Usuário:");

        jLSenha.setText("Senha:");

        jButtonSair.setText("Sair");
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });

        jButtonEntrar.setText("Entrar");
        jButtonEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEntrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
                getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(
                        layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(
                                layout.createParallelGroup(
                                        javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLSenha)
                                .addComponent(jLUsuario))
                        .addGap(18, 18, 18)
                        .addGroup(
                                layout.createParallelGroup(
                                        javax.swing.GroupLayout.Alignment.LEADING,
                                        false)
                                .addGroup(
                                        layout.createSequentialGroup()
                                        .addComponent(
                                                jButtonSair)
                                        .addPreferredGap(
                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                35,
                                                Short.MAX_VALUE)
                                        .addComponent(
                                                jButtonEntrar))
                                .addComponent(jTFUsuario)
                                .addComponent(jTFSenha))
                        .addContainerGap(32, Short.MAX_VALUE)));
        layout.setVerticalGroup(layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(
                        layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(
                                layout.createParallelGroup(
                                        javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLUsuario)
                                .addComponent(
                                        jTFUsuario,
                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(
                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(
                                layout.createParallelGroup(
                                        javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLSenha)
                                .addComponent(
                                        jTFSenha,
                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(
                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                20, Short.MAX_VALUE)
                        .addGroup(
                                layout.createParallelGroup(
                                        javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButtonSair)
                                .addComponent(jButtonEntrar))
                        .addContainerGap()));

        getAccessibleContext().setAccessibleName("SiSAD");

        pack();
    }// </editor-fold>                        

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonSairActionPerformed
        System.exit(0);
    }// GEN-LAST:event_jButtonSairActionPerformed

    private void jButtonEntrarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonEntrarActionPerformed

        String usuario = jTFUsuario.getText();
        String senha = new String(jTFSenha.getPassword());

        if (usuario.equals("sisad") && senha.equals(senhaAtual())) {
            FrmConfig_v4 frm;
            try {
                frm = new FrmConfig_v4();
                frm.setLocationRelativeTo(null);
                frm.setVisible(true);
                dispose();
            } catch (FileNotFoundException ex) {
                Logger.getLogger(FrmLoggin.class.getName()).log(Level.SEVERE,
                        null, ex);
            }
        } else {

            if (usuario.equals("root") && senha.equals(senhaAtual())) {
                FrmConfig_v4 frm;
                try {
                    frm = new FrmConfig_v4();
                    frm.setLocationRelativeTo(null);
                    frm.setVisible(true);
                    dispose();
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(FrmLoggin.class.getName()).log(Level.SEVERE,
                            null, ex);
                }
            } else {
                jTFSenha.setText("");
                jTFSenha.grabFocus();
                String msg = ("Usuário/senha incorretos");
                JOptionPane.showMessageDialog(this, msg, null, WIDTH);
            }

        }
    }// GEN-LAST:event_jButtonEntrarActionPerformed

    public String senhaAtual() {

        if (jTFUsuario.getText().equals("sisad")) {
            int fixo = 14;
            int ano = Calendar.getInstance().get(Calendar.YEAR);
            int mes = Calendar.getInstance().get(Calendar.MONTH);
            int dia = Calendar.getInstance().get(Calendar.DATE);
            int hora = Calendar.getInstance().get(Calendar.HOUR);
            int soma = (ano + mes + dia) * hora * fixo;
            return String.valueOf(soma);
        }

        if (jTFUsuario.getText().equals("root")) {
            String senha = "sisad";
            return senha;
        }

        return senhaAtual();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
                    .getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmLoggin.class.getName()).log(
                    java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmLoggin.class.getName()).log(
                    java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmLoggin.class.getName()).log(
                    java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmLoggin.class.getName()).log(
                    java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmLoggin().setVisible(true);
            }
        });
    }

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jButtonEntrar;
	private javax.swing.JButton jButtonSair;
	private javax.swing.JLabel jLSenha;
	private javax.swing.JLabel jLUsuario;
	private javax.swing.JPasswordField jTFSenha;
	private javax.swing.JTextField jTFUsuario;
	// End of variables declaration//GEN-END:variables
}
